
[server]
port = 5035
sslCertFile = "/etc/nginx/ssl/datapai_fullchain.crt"
sslKeyFile = "/etc/nginx/ssl/private.key"

[theme]
primaryColor="#2af598"
backgroundColor="#111827"
secondaryBackgroundColor="#1f2937"
textColor="#9ca3af"
font="sans serif"
